// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaknaAPI.Models
{
    public partial class UserAccount
    {
        public int UaccountId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public virtual User Uaccount { get; set; }
    }
}